/** @license SPDX-License-Identifier: Apache-2.0 */
import { useState } from 'react';
import { CalibrationSample, GradingQuestion, NormalizedDocument, VisionValidationResult } from '../../domain/types';

export default function AnnotatedSubmissionView({ document, validation, validationPhase = 'idle', samples, questions }: { document?: NormalizedDocument; validation?: VisionValidationResult; validationPhase?: 'idle' | 'loading' | 'extracting' | 'ready' | 'error'; samples: CalibrationSample[]; questions: GradingQuestion[] }) {
  const [dimensions, setDimensions] = useState<Record<number, { width: number; height: number }>>({});
  const pages = document?.resources.filter(resource => resource.role === 'source-page') ?? [];
  if (!pages.length) return <p className="p-8 text-center text-sm text-slate-500">原始答卷页面尚未加载，请返回上传质检重新解析。</p>;
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
    <div className="space-y-4">{validationPhase === 'loading' || validationPhase === 'extracting' ? <p className="rounded-xl bg-sky-50 p-3 text-sm font-bold text-sky-800">{validationPhase === 'loading' ? '正在读取逐题标注' : '正在更新逐题标注'}，原始答卷仍可查看。</p> : null}{validationPhase === 'error' ? <p className="rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">尚无逐题标注，可返回上传质检执行“提取逐题答案”。</p> : null}{pages.map((page, index) => { const pageNumber = page.pageNumber ?? index + 1; const size = dimensions[pageNumber]; const items = validation?.items.filter(item => item.region.pageNumber === pageNumber) ?? []; return <div key={page.id} className="relative overflow-hidden border border-slate-200 bg-white dark:border-zinc-800"><img src={page.publicUrl} alt={`学生答卷第 ${pageNumber} 页`} className="block h-auto w-full" onLoad={event => setDimensions(current => ({ ...current, [pageNumber]: { width: event.currentTarget.naturalWidth, height: event.currentTarget.naturalHeight } }))} />{size ? items.map(item => { const question = questions.find(candidate => candidate.displayNo === item.displayNo); const sample = samples.find(candidate => candidate.questionId === question?.id); const score = sample?.teacherScore ?? sample?.aiScore; return <div key={item.displayNo} title={sample?.teacherReason ?? sample?.gradingReason} className="pointer-events-none absolute border-2 border-emerald-600 bg-emerald-400/10" style={{ left: `${item.region.x / size.width * 100}%`, top: `${item.region.y / size.height * 100}%`, width: `${item.region.width / size.width * 100}%`, height: `${item.region.height / size.height * 100}%` }}><span className="absolute left-0 top-0 -translate-y-full bg-emerald-700 px-2 py-1 text-[11px] font-black text-white">第 {item.displayNo} 题 · {score ?? '-'} / {sample?.fullScore ?? question?.score ?? '-'}</span></div>; }) : null}</div>; })}</div>
    <aside className="space-y-2">{samples.map(sample => { const question = questions.find(item => item.id === sample.questionId); return <article key={sample.id} className="rounded-2xl border border-slate-200 p-4 dark:border-zinc-800"><div className="flex justify-between gap-3"><strong>第 {question?.displayNo ?? '-'} 题</strong><strong className="text-emerald-700">{sample.teacherScore ?? sample.aiScore ?? '-'} / {sample.fullScore}</strong></div><p className="mt-2 text-xs leading-5 text-slate-500">{sample.teacherReason ?? sample.gradingReason ?? '暂无评分说明'}</p></article>; })}</aside>
  </div>;
}
